apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: domain-tech-stack-wizard
  title: Domain-Based Tech Stack Wizard
  description: Select a domain, then choose a tech stack type, and pick options dynamically.
  tags:
    - generator
    - frontend
    - backend
    - database

spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Project Stack Configuration
      type: object
      required:
        - domain
        - stackType
        - stackOption
      properties:
        domain:
          title: Select a Domain
          type: string
          enum:
            - Banking
            - Insurance
            - HealthCare
            - Education

        stackType:
          title: Select Tech Stack Type
          type: string
          enum:
            - UI Framework
            - Backend Platform
            - Database

        stackOption:
          title: Select Stack Option
          type: string
          # No enum here, must be defined in dependencies for dynamic behavior

      dependencies:
        domain:
          oneOf:
            # Banking
            - properties:
                domain:
                  const: Banking
                stackType:
                  const: UI Framework
                stackOption:
                  title: UI Framework Options (Banking)
                  type: string
                  enum: [Vue.js, Next.js, Typescript]
              required:
                - stackOption

            - properties:
                domain:
                  const: Banking
                stackType:
                  const: Backend Platform
                stackOption:
                  title: Backend Platform Options (Banking)
                  type: string
                  enum: [Java, Python, Ruby]
              required:
                - stackOption

            - properties:
                domain:
                  const: Banking
                stackType:
                  const: Database
                stackOption:
                  title: Database Options (Banking)
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

            # Insurance
            - properties:
                domain:
                  const: Insurance
                stackType:
                  const: UI Framework
                stackOption:
                  title: UI Framework Options (Insurance)
                  type: string
                  enum: [React, Angular]
              required:
                - stackOption

            - properties:
                domain:
                  const: Insurance
                stackType:
                  const: Backend Platform
                stackOption:
                  title: Backend Platform Options (Insurance)
                  type: string
                  enum: [Scala, Go, Django]
              required:
                - stackOption

            - properties:
                domain:
                  const: Insurance
                stackType:
                  const: Database
                stackOption:
                  title: Database Options (Insurance)
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

            # HealthCare
            - properties:
                domain:
                  const: HealthCare
                stackType:
                  const: UI Framework
                stackOption:
                  title: UI Framework Options (HealthCare)
                  type: string
                  enum: [Three.js, ReactJs, Angular 2+]
              required:
                - stackOption

            - properties:
                domain:
                  const: HealthCare
                stackType:
                  const: Backend Platform
                stackOption:
                  title: Backend Platform Options (HealthCare)
                  type: string
                  enum: [Springboot, ASP.NET]
              required:
                - stackOption

            - properties:
                domain:
                  const: HealthCare
                stackType:
                  const: Database
                stackOption:
                  title: Database Options (HealthCare)
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

            # Education
            - properties:
                domain:
                  const: Education
                stackType:
                  const: UI Framework
                stackOption:
                  title: UI Framework Options (Education)
                  type: string
                  enum: [Vue.js, Next.js, Typescript, Three.js, ReactJs, Angular 2+]
              required:
                - stackOption

            - properties:
                domain:
                  const: Education
                stackType:
                  const: Backend Platform
                stackOption:
                  title: Backend Platform Options (Education)
                  type: string
                  enum:
                    - Java
                    - Python
                    - Ruby
                    - PHP Kotlin
                    - C sharp
                    - Perl
                    - Scala
                    - Go
                    - Djangi
                    - Springboot
                    - ASP.NET
              required:
                - stackOption

            - properties:
                domain:
                  const: Education
                stackType:
                  const: Database
                stackOption:
                  title: Database Options (Education)
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          domain: ${{ parameters.domain }}
          stackType: ${{ parameters.stackType }}
          stackOption: ${{ parameters.stackOption }}

  output:
    links:
      - title: Review Selection
        url: https://example.com/review?domain=${{ parameters.domain }}&stackType=${{ parameters.stackType }}&stackOption=${{ parameters.stackOption }}
        icon: visibility

      - title: Open in VSCode
        icon: code
        url: https://vscode.dev/?folder=${{ parameters.domain }}-${{ parameters.stackType }}-${{ parameters.stackOption }}

      - title: Open in Replit
        icon: rocket
        url: https://replit.com/new/github/${{ parameters.domain }}-${{ parameters.stackType }}-${{ parameters.stackOption }}

      - title: Open in Catalog
        icon: catalog
        entityRef: component:default/my-service
