apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: domain-tech-stack-wizard
  title: Domain-Based Tech Stack Wizard
  description: Select a domain, then choose a tech stack type, and pick options dynamically.
  tags:
    - generator
    - frontend
    - backend
    - database

spec:
  owner: user:your-username
  type: service

  parameters:
    - title: Project Stack Configuration
      type: object
      required:
        - domain
        - stackType
        - stackOption
      properties:
        domain:
          title: Select a Domain
          type: string
          enum:
            - Banking
            - Insurance
            - HealthCare
            - Education

        stackType:
          title: Select Tech Stack Type
          type: string
          enum:
            - UI Framework
            - Backend Platform
            - Database

        stackOption:
          title: Select Stack Option
          type: string

      dependencies:
        domain:
          oneOf:
            # Banking domain options based on stackType
            - properties:
                domain:
                  const: Banking
                stackType:
                  const: UI Framework
                stackOption:
                  type: string
                  enum: [Vue.js, Next.js, Typescript]
              required:
                - stackOption
            - properties:
                domain:
                  const: Banking
                stackType:
                  const: Backend Platform
                stackOption:
                  type: string
                  enum: [Java, Python, Ruby]
              required:
                - stackOption
            - properties:
                domain:
                  const: Banking
                stackType:
                  const: Database
                stackOption:
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

            # Insurance domain options
            - properties:
                domain:
                  const: Insurance
                stackType:
                  const: UI Framework
                stackOption:
                  type: string
                  enum: [React, Angular]
              required:
                - stackOption
            - properties:
                domain:
                  const: Insurance
                stackType:
                  const: Backend Platform
                stackOption:
                  type: string
                  enum: [Scala, Go, Django]
              required:
                - stackOption
            - properties:
                domain:
                  const: Insurance
                stackType:
                  const: Database
                stackOption:
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

            # HealthCare domain options
            - properties:
                domain:
                  const: HealthCare
                stackType:
                  const: UI Framework
                stackOption:
                  type: string
                  enum: [Three.js, ReactJs, Angular 2+]
              required:
                - stackOption
            - properties:
                domain:
                  const: HealthCare
                stackType:
                  const: Backend Platform
                stackOption:
                  type: string
                  enum: [Springboot, ASP.NET]
              required:
                - stackOption
            - properties:
                domain:
                  const: HealthCare
                stackType:
                  const: Database
                stackOption:
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

            # Education domain options
            - properties:
                domain:
                  const: Education
                stackType:
                  const: UI Framework
                stackOption:
                  type: string
                  enum: [Vue.js, Next.js, Typescript, Three.js, ReactJs, Angular 2+]
              required:
                - stackOption
            - properties:
                domain:
                  const: Education
                stackType:
                  const: Backend Platform
                stackOption:
                  type: string
                  enum:
                    - Java
                    - Python
                    - Ruby
                    - PHP Kotlin
                    - C sharp
                    - Perl
                    - Scala
                    - Go
                    - Djangi
                    - Springboot
                    - ASP.NET
              required:
                - stackOption
            - properties:
                domain:
                  const: Education
                stackType:
                  const: Database
                stackOption:
                  type: string
                  enum: [MYSQL, PostgreSQL]
              required:
                - stackOption

  steps:
    - id: review
      name: Review Selections
      action: pass
      input:
        message: |
          Domain: ${{ parameters.domain }}
          Tech Stack Type: ${{ parameters.stackType }}
          Selected Option: ${{ parameters.stackOption }}

  output:
    links:
      - title: Review
        url: '#'
